version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - api_network
    entrypoint: ["tail", "-f", "/dev/null"]

  api:
    build:
      context: .
      dockerfile: ./RackApi/Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./RackApi/ocelot.json:/app/ocelot.json
    networks:
      - api_network
    entrypoint: ["tail", "-f", "/dev/null"]

  user:
    build:
      context: .
      dockerfile: ./RackApi.User/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - api_network
    entrypoint: ["tail", "-f", "/dev/null"]

  message:
    build:
      context: .
      dockerfile: ./RackApi.Chat/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - api_network
    entrypoint: ["tail", "-f", "/dev/null"]

networks:
  api_network:
    driver: bridge