version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - api_network
        
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'RackUsers, RackChats'
    volumes:
      - db_data_users:/var/lib/postgresql/users
      - db_data_users:/var/lib/postgresql/chats
    networks:
      - api_network
  
  rackapi:
    build:
      context: .
      dockerfile: ./RackApi/Dockerfile
    ports:
      - "5283:80"
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./RackApi/ocelot.json:/app/ocelot.json
    networks:
      - api_network

  message:
    build:
      context: .
      dockerfile: ./RackApi.Chat/Dockerfile
    ports:
      - "5012:80"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - api_network

  user:
    build:
      context: .
      dockerfile: ./RackApi.User/Dockerfile
    ports:
      - "5114:80"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - api_network

networks:
  api_network:

volumes:
  rabbitmq_data:
  db_data_users:
  db_data_chats: