version: '3.8'

services:
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .
      dockerfile: ./RackApi/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq

  user:
    build:
      context: .
      dockerfile: ./RackApi.User/Dockerfile
    depends_on:
      - rabbitmq

  chat:
    build:
      context: .
      dockerfile: ./RackApi.Chat/Dockerfile
    depends_on:
      - rabbitmq

  integration-tests:
    build:
      context: .
      dockerfile: /RackApi.IntegrationTest/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - api
      - user
      - chat