version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - api_network
    entrypoint: ["tail", "-f", "/dev/null"]

  api:
    build:
      context: .
      dockerfile: ./RackApi/Dockerfile
    ports:
      - "5283:80"
    depends_on:
      - rabbitmq
    volumes:
      - ./RackApi/ocelot.json:/app/ocelot.json
    networks:
      - api_network
    entrypoint: ["tail", "-f", "/dev/null"]

  user:
    build:
      context: .
      dockerfile: ./RackApi.User/Dockerfile
    ports:
      - "5114:80"
    depends_on:
      - rabbitmq
    networks:
      - api_network
    entrypoint: ["tail", "-f", "/dev/null"]

  message:
    build:
      context: .
      dockerfile: ./RackApi.Chat/Dockerfile
    ports:
      - "5012:80"
    depends_on:
      - rabbitmq
    networks:
      - api_network
    entrypoint: ["tail", "-f", "/dev/null"]

  integration-tests:
    build:
      context: .
      dockerfile: ./RackApi.IntegrationTest/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - api
      - user
      - chat
    networks:
      - api_network
    entrypoint: ["tail", "-f", "/dev/null"]

networks:
  api_network:
    driver: bridge