version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - api_network

  api:
    build:
      context: .
      dockerfile: ./RackApi/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq
    volumes:
      - ./RackApi/ocelot.json:/app/ocelot.json
    networks:
      - api_network

  user:
    build:
      context: .
      dockerfile: ./RackApi.User/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - api_network

  chat:
    build:
      context: .
      dockerfile: ./RackApi.Chat/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - api_network

  integration-tests:
    build:
      context: .
      dockerfile: ./RackApi.IntegrationTest/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - api
      - user
      - chat
    networks:
      - api_network

networks:
  api_network:
    driver: bridge