version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    network_mode: "host"
    entrypoint: ["tail", "-f", "/dev/null"]

  api:
    build:
      context: .
      dockerfile: ./RackApi/Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./RackApi/ocelot.json:/app/ocelot.json
    network_mode: "host"
    entrypoint: ["tail", "-f", "/dev/null"]

  user:
    build:
      context: .
      dockerfile: ./RackApi.User/Dockerfile
    depends_on:
      - rabbitmq
    network_mode: "host"
    entrypoint: ["tail", "-f", "/dev/null"]

  message:
    build:
      context: .
      dockerfile: ./RackApi.Chat/Dockerfile
    depends_on:
      - rabbitmq
    network_mode: "host"
    entrypoint: ["tail", "-f", "/dev/null"]
