FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["RackApi.User/RackApi.User.csproj", "RackApi.User/"]
RUN dotnet restore "RackApi.User/RackApi.User.csproj"
COPY . .
WORKDIR "/src/RackApi.User"
RUN dotnet build "RackApi.User.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "RackApi.User.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY ./RackApi.User/appsettings.json ./
EXPOSE 5114
ENTRYPOINT ["dotnet", "RackApi.User.dll"]
