apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
#    kubernetes.io/ingress.class: "gce"
#    kubernetes.io/ingress.global-static-ip-name: "ingress-rack"
    ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: test.localhost
      http:
        paths:
          - path: /User
            pathType: Prefix
            backend:
              service:
                name: user
                port:
                  number: 5114
          - path: /Message
            pathType: Prefix
            backend:
              service:
                name: message
                port:
                  number: 5012