apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  strategy: {}
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - image: jornkersten/rackusers
          name: user
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "50m"
      restartPolicy: Always
status: {}

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 90