# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and run services
        run: |
          docker-compose up -d --build

      - name: Make Health Check Script Executable
        run: chmod +x ./Health-check-RabbitMQ.sh

      - name: Health check
        run: ./Health-check-RabbitMQ.sh

      - name: Run tests
        run: |
          dotnet test RackApi.IntegrationTest/RackApi.IntegrationTest.csproj

      - name: Capture Docker Compose Logs
        if: always()
        run: docker-compose logs

      - name: Clean up
        run: |
          docker-compose down