# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and run services
        run: |
          docker-compose up -d --build
          docker-compose exec -T rabbitmq sh -c 'until rabbitmqctl await_startup; do sleep 1; done'

#      - name: Wait for RabbitMQ to be ready
#        run: |
#          until nc -zv localhost 5672; do
#            echo "Waiting for RabbitMQ to start..."
#            sleep 1
#          done
#          echo "RabbitMQ is ready!"

      - name: Run tests
        run: |
          dotnet test RackApi.IntegrationTest/RackApi.IntegrationTest.csproj

      - name: Capture Docker Compose Logs
        if: always()
        run: docker-compose logs

      - name: Clean up
        run: |
          docker-compose down