# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and run services
        run: |
          docker-compose -f docker-compose.test.yml up -d --build

      - name: Run tests
        run: |
          dotnet test 

      - name: Clean up
        run: |
          docker-compose -f docker-compose.test.yml down